# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/design_1_smartconnect_0_1.xci
# IP: The module: 'design_1_smartconnect_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/bd_886d.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_0/bd_886d_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_1/bd_886d_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_2/bd_886d_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_3/bd_886d_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_4/bd_886d_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_5/bd_886d_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_6/bd_886d_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_7/bd_886d_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_8/bd_886d_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_9/bd_886d_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_10/bd_886d_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_11/bd_886d_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_12/bd_886d_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_13/bd_886d_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_14/bd_886d_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_15/bd_886d_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_16/bd_886d_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_17/bd_886d_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_18/bd_886d_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_19/bd_886d_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_20/bd_886d_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_21/bd_886d_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_22/bd_886d_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_23/bd_886d_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_24/bd_886d_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_25/bd_886d_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_26/bd_886d_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_27/bd_886d_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_28/bd_886d_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_29/bd_886d_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_30/bd_886d_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_31/bd_886d_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_32/bd_886d_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_1/bd_886d_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_1/bd_886d_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_2/bd_886d_arinsw_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_3/bd_886d_rinsw_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_4/bd_886d_awinsw_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_5/bd_886d_winsw_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_6/bd_886d_binsw_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_7/bd_886d_aroutsw_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_8/bd_886d_routsw_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_9/bd_886d_awoutsw_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_10/bd_886d_woutsw_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_11/bd_886d_boutsw_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_12/bd_886d_arni_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_13/bd_886d_rni_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_14/bd_886d_awni_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_15/bd_886d_wni_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_16/bd_886d_bni_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_20/bd_886d_s00a2s_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_21/bd_886d_sarn_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_22/bd_886d_srn_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_23/bd_886d_sawn_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_24/bd_886d_swn_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_25/bd_886d_sbn_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_26/bd_886d_m00s2a_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_27/bd_886d_m00arn_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_28/bd_886d_m00rn_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_29/bd_886d_m00awn_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_30/bd_886d_m00wn_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_31/bd_886d_m00bn_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_smartconnect_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_smartconnect_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/design_1_smartconnect_0_1.xci
# IP: The module: 'design_1_smartconnect_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/bd_886d.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_0/bd_886d_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_1/bd_886d_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_2/bd_886d_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_3/bd_886d_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_4/bd_886d_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_5/bd_886d_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_6/bd_886d_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_7/bd_886d_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_8/bd_886d_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_9/bd_886d_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_10/bd_886d_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_11/bd_886d_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_12/bd_886d_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_13/bd_886d_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_14/bd_886d_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_15/bd_886d_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_16/bd_886d_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_17/bd_886d_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_18/bd_886d_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_19/bd_886d_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_20/bd_886d_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_21/bd_886d_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_22/bd_886d_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_23/bd_886d_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_24/bd_886d_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_25/bd_886d_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_26/bd_886d_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_27/bd_886d_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_28/bd_886d_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_29/bd_886d_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_30/bd_886d_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_31/bd_886d_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_32/bd_886d_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_1/bd_886d_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_1/bd_886d_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_2/bd_886d_arinsw_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_3/bd_886d_rinsw_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_4/bd_886d_awinsw_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_5/bd_886d_winsw_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_6/bd_886d_binsw_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_7/bd_886d_aroutsw_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_8/bd_886d_routsw_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_9/bd_886d_awoutsw_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_10/bd_886d_woutsw_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_11/bd_886d_boutsw_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_12/bd_886d_arni_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_13/bd_886d_rni_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_14/bd_886d_awni_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_15/bd_886d_wni_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_16/bd_886d_bni_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_20/bd_886d_s00a2s_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_21/bd_886d_sarn_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_22/bd_886d_srn_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_23/bd_886d_sawn_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_24/bd_886d_swn_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_25/bd_886d_sbn_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_26/bd_886d_m00s2a_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_27/bd_886d_m00arn_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_28/bd_886d_m00rn_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_29/bd_886d_m00awn_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_30/bd_886d_m00wn_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_31/bd_886d_m00bn_0_ooc.xdc

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_smartconnect_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ryansundermeyer/vivado-projects/axi_test/axi_test.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_smartconnect_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
