# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/vivado-projects/Basys-3-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bcd_0_0/design_1_bcd_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_bcd_0_0 || ORIG_REF_NAME==design_1_bcd_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fsm_0_0/design_1_fsm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_fsm_0_0 || ORIG_REF_NAME==design_1_fsm_0_0} -quiet] -quiet

# XDC: c:/Users/ryansundermeyer/vivado-projects/lab3_7seg_fsm/lab3_7seg_fsm.gen/sources_1/bd/design_1/design_1_ooc.xdc
