# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/vivado-projects/Zybo-Z7-Master.xdc

# Block Designs: bd/design_2/design_2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_0 || ORIG_REF_NAME==design_2_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_increment_pwm_us_0_0/design_2_increment_pwm_us_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_increment_pwm_us_0_0 || ORIG_REF_NAME==design_2_increment_pwm_us_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_pwm_gen_0_0/design_2_pwm_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_pwm_gen_0_0 || ORIG_REF_NAME==design_2_pwm_gen_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_util_vector_logic_0_0/design_2_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_util_vector_logic_0_0 || ORIG_REF_NAME==design_2_util_vector_logic_0_0} -quiet] -quiet

# XDC: c:/Users/ryansundermeyer/vivado-projects/pwm_gen/pwm_gen.gen/sources_1/bd/design_2/design_2_ooc.xdc
